// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    'components/Button/index': {
      id: 'components/Button/index',
      path: 'components/button',
      parentId: 'DocLayout',
      meta: { _atom_route: true },
    },
    'components/Checkbox/index': {
      id: 'components/Checkbox/index',
      path: 'components/checkbox',
      parentId: 'DocLayout',
      meta: { _atom_route: true },
    },
    'components/Input/index': {
      id: 'components/Input/index',
      path: 'components/input',
      parentId: 'DocLayout',
      meta: { _atom_route: true },
    },
    'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'dumi-context-layout' },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__404" */ 'D:/Work/Libs/kelvinward-libs/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ 'D:/Work/Libs/kelvinward-libs/.dumi/tmp/dumi/theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */ 'D:/Work/Libs/kelvinward-libs/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'components/Button/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "components__Button__index.md" */ 'D:/Work/Libs/kelvinward-libs/src/components/Button/index.md'
          ),
      ),
      'components/Checkbox/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "components__Checkbox__index.md" */ 'D:/Work/Libs/kelvinward-libs/src/components/Checkbox/index.md'
          ),
      ),
      'components/Input/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "components__Input__index.md" */ 'D:/Work/Libs/kelvinward-libs/src/components/Input/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */ 'D:/Work/Libs/kelvinward-libs/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
