// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  frontmatter as fm0,
  toc as t0,
} from 'D:/Work/Libs/kelvinward-libs/src/components/Button/index.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/Work/Libs/kelvinward-libs/src/components/Button/index.md?type=demo-index';
import {
  frontmatter as fm1,
  toc as t1,
} from 'D:/Work/Libs/kelvinward-libs/src/components/Checkbox/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/Work/Libs/kelvinward-libs/src/components/Checkbox/index.md?type=demo-index';
import {
  frontmatter as fm2,
  toc as t2,
} from 'D:/Work/Libs/kelvinward-libs/src/components/Input/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/Work/Libs/kelvinward-libs/src/components/Input/index.md?type=demo-index';

export const filesMeta = {
  'components/Button/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__components" */ 'D:/Work/Libs/kelvinward-libs/src/components/Button/index.md?type=text'
      ),
  },
  'components/Checkbox/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__components" */ 'D:/Work/Libs/kelvinward-libs/src/components/Checkbox/index.md?type=text'
      ),
  },
  'components/Input/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__components" */ 'D:/Work/Libs/kelvinward-libs/src/components/Input/index.md?type=text'
      ),
  },
};

export { tabs as tabsMeta } from './tabs';
