// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/Work/Libs/kelvinward-libs/node_modules/dumi/theme-default/builtins/Badge/index.js';
